### ISSUE TITLE
如何在代码中使用 `eval` 模块？

### ISSUE THREAD

**Issue by situche** [ZelateCalcite/emnlp2024-zzh#1]
我在运行项目时遇到了一些问题，具体是关于https://github.com/ZelateCalcite/TOPT_NER下的 `eval` 模块。该模块并非是一个通过 `pip` 安装的库，因此我不确定它的来源。在作者提供的文件中也没有相关的模块，而如果不使用该模块程序就无法运行，请问这个模块该如何获得

**Comment by ZelateCalcite** [comment]
抱歉，在初始化仓库时遗漏了`eval.py`，我之后会更新仓库添加这个文件

**Comment by ZelateCalcite** [comment]
`eval.py`已更新，现在代码应该可以运行

**Comment by situche** [comment]
> `eval.py`已更新，现在代码应该可以运行

好的，谢谢
