### ISSUE TITLE
Pls update the prompts to generate synthetic dataset

### ISSUE THREAD

**Issue by aivolcano** [ZelateCalcite/emnlp2024-zzh#2]
Hi

Could you update the prompt for generating synthetic data? This part is very important. 

Thank you so much

**Comment by ZelateCalcite** [comment]
We will update the prompt  in `llama_generation` soon later

**Comment by aivolcano** [comment]
Thank you so much

**Comment by ZelateCalcite** [comment]
Please check the updated code and the prompt is in `llama_generation/generate.py`

**Comment by aivolcano** [comment]
Good job. thx!!!
